<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_tags
 *
 * @copyright   Copyright (C) 2005 - 2017 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

use Joomla\CMS\Factory;
use Joomla\CMS\Layout\LayoutHelper;

defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers/html');
JHtml::_('behavior.core');
JHtml::_('formbehavior.chosen', 'select');

// Get the user object.
$user = Factory::getUser();



$bootstrapclass = 'col-md-' . $this->params->get('bootstrapcols', '6');
$tags = $this->item->tags->itemTags;
$images = json_decode($this->item->images);

Factory::getDocument()->addScriptDeclaration("
		var resetFilter = function() {
		document.getElementById('filter-search').value = '';
	}
");
?>


<div class="element-item col-12 <?php echo $bootstrapclass; ?>
<?php foreach ($this->item->tags->itemTags as $tag) {
	echo ' ' . $tag->alias . ' ';
}

foreach ($this->item->jcfields as $jcfield) {
	echo ' ' . specialchars($jcfield->value) . ' ';
}

?>">

	<div class="inner">
		<?php echo LayoutHelper::render('joomla.content.blog_style_default_item_title', $this->item); ?>

		<?php // Content is generated by content plugin event "onContentAfterTitle" ?>
		<?php echo $this->item->event->afterDisplayTitle; ?>

		<div class="row">

			<?php if ($this->item->event->beforeDisplayContent) { ?>
				<div class="col-12">
					<?php echo $this->item->event->beforeDisplayContent; ?>
				</div>
			<?php } ?>

			<div class="col-6">
				<?php echo LayoutHelper::render('joomla.content.intro_image', $this->item); ?>
			</div>

			<?php if ($this->item->introtext) { ?>
				<div class="col-6">
					<?php echo $this->item->introtext; ?>
				</div>
			<?php } ?>

			<?php if ($this->item->event->afterDisplayContent) { ?>
				<div class="col-12">
					<?php echo $this->item->event->afterDisplayContent; ?>
				</div>
			<?php } ?>

			<?php if ($this->item->tags->itemTags) { ?>
				<div class="col-12">
					<ul class="tags">
						<?php
						foreach ($this->item->tags->itemTags as $tag) {
							echo '<li itemprop="keywords">';
							echo $tag->title;
							echo '</li>';
						}	?>
					</ul>
				</div>
			<?php } ?>
		</div>
	</div>
</div>

